[package]
name = "egomoose/character-animate"
version = "0.0.0"
description = "https://github.com/EgoMoose/character-animate"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]